name: 'Scope for .NET'
author: 'Undefined Labs'
description: 'Automatically instruments and runs your tests using the Scope .NET agent'
inputs:
  command:  # command to run inside the scope-run wrapper
    description: 'Command to run inside the scope-run wrapper'
    required: false
  dsn: # scope dsn
    description: 'Scope DSN'
    required: true
  use-solutions: # use solutions file
    description: 'Run the scope-run command from the solutions file folder'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'
