name: 'scope-for-dotnet'
description: 'Scope agent for dotnet'
inputs:
  command:  # command to run inside the scope-run wrapper
    description: 'Command to run inside the scope-run wrapper'
    required: false
  apikey: # api key
    description: 'Scope API key'
    required: false
  dsn: # scope dsn
    description: 'Scope DSN'
    required: false
  use-solutions: # use solutions file
    description: 'Use solutions files'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
